# Generated by Django 2.0.4 on 2018-06-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[(1, 'ENTRADA'), (2, 'SALIDA')], max_length=1)),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='kardex',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Producto'),
        ),
        migrations.AddField(
            model_name='catalogoproducto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Empresa'),
        ),
        migrations.AddField(
            model_name='catalogoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Producto'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Sucursal'),
        ),
    ]
