# Generated by Django 2.0.4 on 2018-06-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestro.Almacen'),
            preserve_default=False,
        ),
    ]
