# Generated by Django 2.0.4 on 2018-06-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0002_stock_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('nivel', models.SmallIntegerField()),
                ('padre', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
