# Generated by Django 2.0.4 on 2018-06-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(to='maestro.Categoria'),
        ),
    ]
